export const quotes = [
  { id: 1, quote: "May the Force be with you.", character: "Obi-Wan Kenobi", movie: "Star Wars", year: 1977 },
  { id: 2, quote: "I’m going to make him an offer he can’t refuse.", character: "Vito Corleone", movie: "The Godfather", year: 1972 },
  { id: 3, quote: "Why so serious?", character: "The Joker", movie: "The Dark Knight", year: 2008 },
  { id: 4, quote: "Here’s looking at you, kid.", character: "Rick Blaine", movie: "Casablanca", year: 1942 },
  { id: 5, quote: "To infinity and beyond!", character: "Buzz Lightyear", movie: "Toy Story", year: 1995 },
  { id: 6, quote: "Keep your friends close, but your enemies closer.", character: "Michael Corleone", movie: "The Godfather Part II", year: 1974 },
  { id: 7, quote: "Life is like a box of chocolates. You never know what you’re gonna get.", character: "Forrest Gump", movie: "Forrest Gump", year: 1994 },
  { id: 8, quote: "Say hello to my little friend!", character: "Tony Montana", movie: "Scarface", year: 1983 },
  { id: 9, quote: "I’ll be back.", character: "Terminator", movie: "The Terminator", year: 1984 },
  { id: 10, quote: "It’s not who I am underneath, but what I do that defines me.", character: "Batman", movie: "Batman Begins", year: 2005 },
  { id: 11, quote: "You can’t handle the truth!", character: "Col. Jessup", movie: "A Few Good Men", year: 1992 },
  { id: 12, quote: "After all, tomorrow is another day!", character: "Scarlett O'Hara", movie: "Gone with the Wind", year: 1939 },
  { id: 13, quote: "With great power comes great responsibility.", character: "Uncle Ben", movie: "Spider-Man", year: 2002 },
  { id: 14, quote: "Houston, we have a problem.", character: "Jim Lovell", movie: "Apollo 13", year: 1995 },
  { id: 15, quote: "Carpe diem. Seize the day, boys.", character: "John Keating", movie: "Dead Poets Society", year: 1989 },
  { id: 16, quote: "I’m the king of the world!", character: "Jack Dawson", movie: "Titanic", year: 1997 },
  { id: 17, quote: "You talking to me?", character: "Travis Bickle", movie: "Taxi Driver", year: 1976 },
  { id: 18, quote: "I see dead people.", character: "Cole Sear", movie: "The Sixth Sense", year: 1999 },
  { id: 19, quote: "Every man dies, not every man really lives.", character: "William Wallace", movie: "Braveheart", year: 1995 },
  { id: 20, quote: "Frankly, my dear, I don’t give a damn.", character: "Rhett Butler", movie: "Gone with the Wind", year: 1939 },
  { id: 21, quote: "You’re gonna need a bigger boat.", character: "Brody", movie: "Jaws", year: 1975 },
  { id: 22, quote: "I am your father.", character: "Darth Vader", movie: "Star Wars: The Empire Strikes Back", year: 1980 },
  { id: 23, quote: "E.T. phone home.", character: "E.T.", movie: "E.T. the Extra-Terrestrial", year: 1982 },
  { id: 24, quote: "Show me the money!", character: "Rod Tidwell", movie: "Jerry Maguire", year: 1996 },
  { id: 25, quote: "Bond. James Bond.", character: "James Bond", movie: "Dr. No", year: 1962 },
  { id: 26, quote: "I’ll have what she’s having.", character: "Customer", movie: "When Harry Met Sally...", year: 1989 },
  { id: 27, quote: "There's no place like home.", character: "Dorothy", movie: "The Wizard of Oz", year: 1939 },
  { id: 28, quote: "I feel the need... the need for speed!", character: "Maverick", movie: "Top Gun", year: 1986 },
  { id: 29, quote: "My precious.", character: "Gollum", movie: "The Lord of the Rings: The Two Towers", year: 2002 },
  { id: 30, quote: "They may take our lives, but they’ll never take our freedom!", character: "William Wallace", movie: "Braveheart", year: 1995 },
  { id: 31, quote: "Hasta la vista, baby.", character: "Terminator", movie: "Terminator 2: Judgment Day", year: 1991 },
  { id: 32, quote: "Just keep swimming.", character: "Dory", movie: "Finding Nemo", year: 2003 },
  { id: 33, quote: "Magic Mirror on the wall, who is the fairest one of all?", character: "Queen", movie: "Snow White and the Seven Dwarfs", year: 1937 },
  { id: 34, quote: "It’s alive! It’s alive!", character: "Dr. Frankenstein", movie: "Frankenstein", year: 1931 },
  { id: 35, quote: "You had me at ‘hello.’", character: "Dorothy Boyd", movie: "Jerry Maguire", year: 1996 },
  { id: 36, quote: "If you build it, he will come.", character: "Voice", movie: "Field of Dreams", year: 1989 },
  { id: 37, quote: "I am Groot.", character: "Groot", movie: "Guardians of the Galaxy", year: 2014 },
  { id: 38, quote: "Here’s Johnny!", character: "Jack Torrance", movie: "The Shining", year: 1980 },
  { id: 39, quote: "Run, Forrest, run!", character: "Jenny", movie: "Forrest Gump", year: 1994 },
  { id: 40, quote: "I drink your milkshake!", character: "Daniel Plainview", movie: "There Will Be Blood", year: 2007 }
];

  